#server:
#  port: 7000
#
#spring:
#  datasource:
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.137.14:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#
#  application:
#    name: gulimall-coupon
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.137.14:8848
#
#
#
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml
#
