server:
  port: 11000

spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.14:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.14:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.bigdata.gulimall.ware: debug

